// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDsaI36lsBgKXtwq3p_biSS65nSuBYURs',
    appId: '1:31873733581:web:306d6f5c22192e9d6faa84',
    messagingSenderId: '31873733581',
    projectId: 'examace-4c703',
    authDomain: 'examace-4c703.firebaseapp.com',
    storageBucket: 'examace-4c703.appspot.com',
    measurementId: 'G-57TQBVDDBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAExnY3bz8yM4od4cWYMXv9vHY3rq_YKoc',
    appId: '1:31873733581:android:5213be45fe3261186faa84',
    messagingSenderId: '31873733581',
    projectId: 'examace-4c703',
    storageBucket: 'examace-4c703.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbacv2TW-qKe7aTkb_UPO7KX4HJP0Hu5Q',
    appId: '1:31873733581:ios:bfa461bb11785a206faa84',
    messagingSenderId: '31873733581',
    projectId: 'examace-4c703',
    storageBucket: 'examace-4c703.appspot.com',
    iosClientId: '31873733581-nuo1962fqg9uav6o0chsmhtut12b9f3c.apps.googleusercontent.com',
    iosBundleId: 'com.sidesshmore.examace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbacv2TW-qKe7aTkb_UPO7KX4HJP0Hu5Q',
    appId: '1:31873733581:ios:c633ef33e2ca81606faa84',
    messagingSenderId: '31873733581',
    projectId: 'examace-4c703',
    storageBucket: 'examace-4c703.appspot.com',
    iosClientId: '31873733581-csojk6tu2aacd9p4jva2hndprihu041t.apps.googleusercontent.com',
    iosBundleId: 'com.example.examace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDsaI36lsBgKXtwq3p_biSS65nSuBYURs',
    appId: '1:31873733581:web:3fe90ecff3346eae6faa84',
    messagingSenderId: '31873733581',
    projectId: 'examace-4c703',
    authDomain: 'examace-4c703.firebaseapp.com',
    storageBucket: 'examace-4c703.appspot.com',
    measurementId: 'G-356JTD7Z60',
  );
}
